### ISSUE TITLE
Request for a video tutorial 

### ISSUE THREAD

**Issue by zakariabijoy** [shibbir/sslcommerz#2]
Please can you make a video tutorial for sslcommerz integration with asp.net core mvc & asp.net core web API with angular?

**Comment by shibbir** [comment]
hello @zakariabijoy, sorry for the late reply :)

I don't have any plan to make a video regarding the integration. I may update the repo with the current version of the frameworks in future.

Otherwise, please follow the guidelines stated here [https://developer.sslcommerz.com/doc/v4](https://developer.sslcommerz.com/doc/v4/)
